[package]
name = "glue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
rand = "0.8.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0.85"
jsonpath-rust = "0.1.6"