[package]
name = "glue"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["Michele Esposito<michele@esposito.codes>"]

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
rand = "0.8.4"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.85"
jsonpath-rust = "0.1.6"
tokio = { version = "1", features = ["full"] }