version: 2.1

workflows:
  version: 2
  build-multi:
    jobs:
      - test
      - build

jobs:
  
  test:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo test

  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo build --release
      - store_artifacts:
          path: ~/project/target/release/glue
          destination: glue-x86_64