version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    working_directory: ~/project
    steps:
      - checkout
      - run: cargo build --release
      - store_artifacts:
          path: ~/project/target/release/glue
