version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - test
#      - build-apple-m1:
#          filters: 
#            tags:
#              only: 
#                - /^v.*/
#            branches:
#              ignore: /.*/
#      - build-apple-x86:
#          filters: 
#            tags:
#              only: 
#                - /^v.*/
#            branches:
#              ignore: /.*/
#      - build-linux:
#          filters: 
#            tags:
#              only: 
#                - /^v.*/
#            branches:
#              ignore: /.*/
      - build-apple-m1
      - build-apple-x86
      - build-linux

jobs:

  build-apple-m1:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: rustup target install aarch64-apple-darwin
      - run: cargo build --release --target aarch64-apple-darwin
      - store_artifacts:
          path: ~/project/target/release/glue
          destination: glue_m1

  build-apple-x86:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: rustup target install x86_64-apple-darwin
      - run: cargo build --release --target x86_64-apple-darwin
      - store_artifacts:
          path: ~/project/target/release/glue
          destination: glue_darwin
  
  build-linux:
    docker:
      - image: cimg/rust:1.63.0
    resource_class: medium
    steps:
      - checkout
      - run: rastup target install x86_64-unknown-linux-gnu
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - store_artifacts:
          path: ~/project/target/release/glue
          destination: glue-linux
  
  test:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo test