on:
  pull_request:
    types: 
      - opened
      - synchronize

jobs:
  release:
    name: pre release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            archive: zip
            os: macos
          - target: x86_64-apple-darwin
            archive: zip
            os: macos
          - target: x86_64-pc-windows-msvc
            archive: zip
            os: win
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz
            os: linux
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
            os: linux
          - target: aarch64-unknown-linux-gnu
            archive: tar.gz tar.xz
            os: linux
          - target: armv7-unknown-linux-gnueabihf
            archive: tar.gz tar.xz
            os: linux
    steps:
      - uses: actions/checkout@master

      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build
        id: bash
        run: bash .github/workflows/scripts/build.sh
        env:
          TARGET: ${{ matrix.target }}
          OS: ${{ matrix.os }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: glue_${{ matrix.target }}
          path: /home/runner/work/glue/glue/target/release/glue