on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            archive: zip
          - target: x86_64-apple-darwin
            archive: zip
          - target: x86_64-pc-windows-msvc
            archive: zip
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: aarch64-unknown-linux-gnu
            archive: tar.gz tar.xz
          - target: armv7-unknown-linux-gnueabihf
            archive: tar.gz tar.xz
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
